kind: PersistentVolume
apiVersion: v1
metadata:
  name: opt-senzing-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/senzing"
